name: Build and Deploy Node.js Backend to Azure App Service - joryanbags

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Instalar dependencias del backend
      - name: Install backend dependencies
        working-directory: ecommerce-backend
        run: npm ci

      # Empaquetar backend para despliegue
      - name: Zip backend for deployment
        working-directory: ecommerce-backend
        run: zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-backend
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-backend

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5CFF246E5A49466F9BD67EC0FC5D9FC7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03BC8030E7FC4FCB9443CBFBDF80C9FD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_42075E09784F472F9CF284240DA39377 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'joryanbags'
          slot-name: 'Production'
          package: .
